import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#cde9d8",
        "tertiary-container": "#9bb7a7",
        "tertiary-fixed-dim": "#b1cdbd",
        "on-primary-fixed": "#2a1700",
        "on-surface": "#e3e1e9",
        secondary: "#cec6b5",
        "surface-bright": "#38393f",
        "on-surface-variant": "#d8c3ad",
        "surface-container-lowest": "#0d0e13",
        "surface-container-highest": "#34343a",
        "surface-dim": "#121318",
        "on-primary-container": "#613b00",
        "primary-fixed-dim": "#ffb95f",
        "surface-container-low": "#1a1b21",
        "secondary-container": "#4e493c",
        "on-tertiary-fixed": "#072016",
        "secondary-fixed": "#ebe2d0",
        "inverse-primary": "#855300",
        "on-secondary-container": "#c0b8a7",
        "primary-fixed": "#ffddb8",
        primary: "#ffc174",
        "on-tertiary": "#1d352a",
        "on-tertiary-container": "#30493c",
        outline: "#a08e7a",
        "on-background": "#e3e1e9",
        "on-secondary-fixed": "#1f1b11",
        "on-secondary-fixed-variant": "#4c463a",
        "inverse-surface": "#e3e1e9",
        "on-primary": "#472a00",
        surface: "#121318",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#cec6b5",
        "outline-variant": "#534434",
        "surface-variant": "#34343a",
        "surface-tint": "#ffb95f",
        tertiary: "#b7d3c2",
        "primary-container": "#f59e0b",
        "error-container": "#93000a",
        "surface-container-high": "#292a2f",
        "on-tertiary-fixed-variant": "#334c40",
        "on-secondary": "#353024",
        "surface-container": "#1e1f25",
        "on-primary-fixed-variant": "#653e00",
        "on-error": "#690005",
        background: "#121318",
        error: "#ffb4ab",
        "inverse-on-surface": "#2f3036",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "margin-desktop": "3rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "gutter-lg": "2rem",
        "margin-mobile": "1rem",
        "gutter-sm": "1rem",
        margin: "2rem",
      },
      fontFamily: {
        "body-sm": ["var(--font-body)", "sans-serif"],
        "code-md": ["var(--font-label)", "sans-serif"],
        "display-lg-mobile": ["var(--font-display)", "serif"],
        "display-lg": ["var(--font-display)", "serif"],
        "label-lg": ["var(--font-label)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-display)", "serif"],
        "headline-sm": ["var(--font-display)", "serif"],
        "label-sm": ["var(--font-label)", "sans-serif"],
        "label-md": ["var(--font-label)", "sans-serif"],
        "headline-lg": ["var(--font-display)", "serif"],
        "headline-md": ["var(--font-display)", "serif"],
        "body-lg": ["var(--font-display)", "serif"],
        "body-md": ["var(--font-body)", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["19px", { lineHeight: "32px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
